name = "honsguiden-monitor"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
PASSWORD = "honsguiden2026"
REPORT_EMAIL = "gabriel.linton@gmail.com"

[triggers]
crons = ["0 6 * * *"]

[[kv_namespaces]]
binding = "MONITOR"
id = "2668dd7d52914c168b1b37e620147388"
